### ISSUE TITLE
always generate different hash even content not changed

### ISSUE THREAD

**Issue by kovenliao** [dsebastien/webpack-sha-hash#6]
Please refer this for detail
https://github.com/dsebastien/webpack-sha-hash/compare/master...kovenliao:fix?expand=1

**Comment by kovenliao** [comment]
Please refer this for detail
https://github.com/dsebastien/webpack-sha-hash/compare/master...kovenliao:fix?expand=1

**Comment by dsebastien** [comment]
Hey there.

Don't hesitate to send a PR, I'll merge it

**Comment by kovenliao** [comment]
PR created. Thanks!
https://github.com/dsebastien/webpack-sha-hash/pull/7/files

**Comment by dsebastien** [comment]
closed by #7

**Comment by dsebastien** [comment]
I've published v1.1.0 containing the fix.
